### ISSUE TITLE
err: ModDataAdd: out of space!!!

### ISSUE THREAD

**Issue by revrsefr** [DalekIRC/no-services#1]
Hi,

wanted to try this out and ive got this error on UnrealIRCd-6.1.5-git.

[19:46]  xxxx [error] ModDataAdd: out of space!!!
[19:46]  xxxx  [error] Could not add ModData for need_login. Please contact developer.
[19:46]  xxxx  [error] Error loading third/no-services: Mod_Init returned -1

Thanks..

**Comment by ValwareIRC** [comment]
Hi there! Thank you for your report.

So the problem here is that there is only a limited space of memory allocated for ModData. This is a choice made by UnrealIRCd and doesn't mean you ran out of space on your computer.

You have two options:
1. Unload some other third-party modules which take up ModData space.
2. Edit UnrealIRCd to give more ModData. You can do this  by editing `unrealircd-6.1.5-git/includes/config.h` and edit the `MODDATA_MAX_CLIENT` and `MODDATA_MAX_LOCAL_CLIENT` (around line 260) to be double their current value (`24` to `48` for example), and then run `make && make install && ./unrealircd rehash`.

**Comment by revrsefr** [comment]
thanks for reply.. will do so.
